groups:
  none:
    permissions:

  member:
    permissions:

  novice:
    permissions:

  master:
    permissions:

  elite:
    permissions:

  rt:
    permissions:
      - plots.admin.command.kick
      - creative.uprank
      - creative.lowerrank

  ls:
    permissions:
      - plots.admin.command.kick
      - creative.uprank
      - creative.lowerrank
