name: creative
version: '${project.version}'
main: ru.codein.creative.Creative
depend:
  - PlotSquared
commands:
  rankup:
    permission: creative.uprank
    description: up rank
    aliases: [up]
  rankdown:
    permission: creative.lowerrank
    description: lower rank
    aliases: [down]
  pcheck:
    permission: creative.pcheck
    description: send plot for review


